spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa0112358)

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

