spring:
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7585885
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sql7585885
    password: 5GeJMvp1DZ

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

